# Generated by Django 5.2.8 on 2025-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=1024, verbose_name='原始商品链接')),
                ('product_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='商品标题')),
                ('product_image_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='商品图片')),
                ('product_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品价格')),
                ('scrape_status', models.CharField(choices=[('PROCESSING', '处理中'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='PROCESSING', max_length=20, verbose_name='抓取状态')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.SmallIntegerField(choices=[(1, '顶'), (-1, '踩')])),
            ],
        ),
    ]
