# Generated by Django 5.2.8 on 2025-11-19 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_created_topics_public',
            field=models.BooleanField(default=True, verbose_name='公开创建的话题'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_followers_public',
            field=models.BooleanField(default=True, verbose_name='公开粉丝列表'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_following_public',
            field=models.BooleanField(default=True, verbose_name='公开关注列表'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_joined_topics_public',
            field=models.BooleanField(default=True, verbose_name='公开加入的话题'),
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
