# Generated by Django 5.2.8 on 2025-11-17 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
