# Generated by Django 5.2.8 on 2025-11-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_topic_subscribers_topicsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='topics/', verbose_name='话题图标'),
        ),
    ]
