# Generated by Django 5.2.8 on 2025-11-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='topics/banners/', verbose_name='话题背景图'),
        ),
    ]
