"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-75gj4fzm6i&k8n&2=iqubt4&l$yv9#e97@3-th_7ku(e2d%m#q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方库
    'rest_framework',
    'corsheaders',
    'django_redis',
    'djoser',                        # <-- 新增
    'rest_framework_simplejwt',      # <-- 新增

    # 我们自己的 Apps (把它们放在这里)
    'users.apps.UsersConfig',
    'topics.apps.TopicsConfig',
    'posts.apps.PostsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'social_shopping_db', # 数据库名
        'USER': 'admin',             # 用户名
        'PASSWORD': 'admin',         # 密码
        'HOST': 'localhost',         # 地址
        'PORT': '5432',              # 默认端口
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 允许来自前端 (localhost:3000) 的所有请求
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

# Celery (使用 Redis 作为 Broker)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# 缓存
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/1", # 使用 1 号数据库，避免和 Celery 冲突
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# settings.py 的末尾
AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 1. (新增) 允许 API 识别"会话 Cookie" 🍪
        #    (这让我们可以在浏览器中测试)
        'rest_framework.authentication.SessionAuthentication',

        # 2. (保留) 允许 API 识别"JWT 令牌" 🔑
        #    (这让我们的前端 App 可以登录)
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # 默认情况下，我们允许任何人进行只读访问
        # 这符合我们之前只读 API 的设置
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    )
}

SIMPLE_JWT = {
    # 访问令牌 (Access Token) 的有效期
    # 用户登录后，这个令牌 1 天后过期，需要重新登录
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),

    # 刷新令牌 (Refresh Token) 的有效期
    # 暂时用不到，但先配上
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # (!!!) 这就是我们添加的修复 (!!!)
    # 告诉 SimpleJWT 接受 "JWT" 作为 header 前缀，
    # 匹配我们前端 AuthContext.tsx 正在发送的 "Authorization: JWT <token>"
    # (注意：它是一个元组，所以要加逗号)
    'AUTH_HEADER_TYPES': ('JWT',),
}

DJOSER = {
    # 我们告诉 Djoser 我们用 JWT，而不是它默认的 Token
    'SERIALIZERS': {
        'user_create': 'users.serializers.UserCreateSerializer', # (下一步创建)
        'user': 'users.serializers.UserSerializer',             # (下一步创建)
        'current_user': 'users.serializers.UserSerializer',   # (下一步创建)
    },
    'PERMISSIONS': {
        'user_create': ['rest_framework.permissions.AllowAny'], # 允许任何人注册
    },
}

LOGIN_REDIRECT_URL = '/api/v1/'