# Generated by Django 5.2.8 on 2025-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', '关注了你'), ('comment', '评论了你的帖子'), ('reply', '回复了你的评论'), ('vote', '赞了你的帖子'), ('message', '给你发了私信')], max_length=20),
        ),
    ]
